#Composeファイルのフォーマットのバージョン
version: "3.6"

#アプリケーションを動かす各要素
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: /start_prod.sh
    #どのネットワークに接続するか
    networks:
      - django-nginx
    env_file:
      - ./.envs/.django
    
    #ホストPC側のディレクトリをDocker内コンテナにマウントさせる
    #またはDockerリソースのボリュームをDocker内コンテナにマウントさせる←
    volumes:
      - .:/code
      - django-static:/backend/static
    depends_on:
      - db

  db:
    #DockerHubにアップされている既存のDockerImageから使う
    image: mysql:5.7.16
    container_name: mysql
    env_file:
      - ./.envs/.mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
        - .db_data:/var/lib/mysql
    ports:
        - 33066:3306
    networks:
      - django-nginx

  adminer:
    image: adminer:4.7-standalone
    container_name: adminer
    ports:
      - 8081:8080
    env_file: ./.envs/.adminer
    depends_on:
      - db
    networks:
      - django-nginx

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
      - ./backend/media:/usr/src/app/media:ro
    depends_on:
      - backend

#volumesでデータボリューム名：コンテナディレクトリとした時の
#名前付きボリュームであることの宣言
volumes:
  django-static:
  django-media:

networks:
  django-nginx:
    driver: bridge
