# Generated by Django 2.2.1 on 2021-08-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210702_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='logo_box_sort',
            field=models.TextField(null=True, verbose_name='ロゴボックス順序'),
        ),
    ]
