# Generated by Django 2.2.1 on 2021-08-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_logo_box_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='logo_box_sort',
        ),
        migrations.AddField(
            model_name='newuser',
            name='logo_box',
            field=models.TextField(null=True, verbose_name='ロゴボックス'),
        ),
    ]
