# Generated by Django 2.2.1 on 2021-08-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210802_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='category',
            field=models.TextField(null=True, verbose_name='カテゴリー'),
        ),
    ]
