# Generated by Django 2.2.1 on 2021-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_newuser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='category_item',
            field=models.TextField(null=True, verbose_name='カテゴリー項目'),
        ),
    ]
