# Generated by Django 2.2.1 on 2021-08-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pagination',
            field=models.TextField(null=True, verbose_name='ページネーション'),
        ),
    ]
