# Generated by Django 2.2.1 on 2021-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_newuser_pagination'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='dark',
            field=models.TextField(default=False, verbose_name='Dark'),
        ),
    ]
