# Generated by Django 2.2.1 on 2021-09-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_newuser_dark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='スーパーユーザー'),
        ),
    ]
