# Generated by Django 2.2.1 on 2022-10-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logobox', '0002_logobox1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logobox1',
            table='user_logo_box',
        ),
    ]
