# Generated by Django 2.2.1 on 2022-10-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logobox', '0003_auto_20221012_0858'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logobox1',
            table='user_logoo_box',
        ),
    ]
