# Generated by Django 2.2.1 on 2022-10-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logobox', '0004_auto_20221018_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoBox1',
        ),
    ]
