# Generated by Django 2.2.1 on 2022-10-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logobox', '0006_logobox1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoBox1',
        ),
    ]
